basic.showIcon(IconNames.House)
basic.forever(function () {
    music.playMelody("C5 B A G D F C C ", 120)
    basic.showIcon(IconNames.Heart)
    basic.pause(100)
    basic.showString("Hello!")
    basic.showIcon(IconNames.Ghost)
    basic.pause(5000)
    basic.clearScreen()
})
